projects:
  tictactoe:
    schemaPath: amplify/backend/api/tictactoe/build/schema.graphql
    includes:
      - src/**/*graphql.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
